version: "3.9"

services:
  db:
    restart: always
    ports: []

  wordpress:
    restart: always
    volumes:
      - ./wp-content/themes/stage-lighting:/var/www/html/wp-content/themes/stage-lighting
      - ./wp-content/plugins/stage-lighting-b2b:/var/www/html/wp-content/plugins/stage-lighting-b2b
      - ./wp-content/plugins/stage-lighting-setup:/var/www/html/wp-content/plugins/stage-lighting-setup
      - wp_data:/var/www/html

  wpcli:
    restart: "no"
